#项目相关配置
layduo:
   #名称
   name: Layduo
   #版本
   version: 4.1.0
   #版本年份
   copyrightYear: 2019
   #实例演示开关
   demoEnabled: true
   #文件路径（ Windows配置D:/layduo/uploadPath，Linux配置 /home/layduo/uploadPath）
   profile: D:/layduo/uploadPath
   #获取ip地址开关
   addressEnabled: true
   
#开发环境配置
server:
   #服务器HTTP端口，默认为80
   port: 8090
   #应用访问路径
   servlet:
      context-path: /
   tomcat:
      #tomcat的URI编码
      uri-encoding: UTF-8
      #tomcat最大线程数，默认为200
      max-threads: 800
      #tomcat启动初始化的线程数，默认为25
      min-spare-threads: 30
      
#日志配置
logging:
   level:
      com.layduo: debug
      org.springframework: warn
      
#用户配置
user:
   password:
      #密码错误{maxRetryCount}次锁定10分钟
      maxRetryCount: 5
      
#spring配置
spring:
   #模板引擎
   thymeleaf:
      mode: HTML
      encoding: UTF-8
      #禁用缓存
      cache: false
   #国际资源信息
   messages:
      #国际化资源文件路径
      basename: static/i18n/messages
   #格式化时间格式
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
   #引用数据源文件
   profiles:
      active: druid
   #文件上传
   servlet:
      multipart:
        #单个文件大小
        max-file-size: 10MB
        #设置总上传文件大小
        max-request-size: 20MB
   #服务模块
   devtools:
      restart:
        #热部署开关 在这里设置false,类加载器还会初始化，但不会监视文件更新。
        enabled: true
        #设置重启的目录
        #additional-paths: src/main/java
        #classpath目录下的WEB-INF文件夹内容修改不重启
        #exclude: WEB-INF/**
      
#mybatis配置
mybatis:
   #搜索指定包别名
   typeAliasesPackage: com.layduo.**.domain
   #配置mapper的扫描，找到所有mapper.xml映射文件
   mapperLocations: classpath*:mapper/**/*Mapper.xml
   #加载mybatis全局的配置文件
   configLocation: classpath:mybatis/mybatis-config.xml
   
#pagehelper分页插件
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
   
#shiro
shiro:
   user:
      #登录地址
      loginUrl: /login
      #权限认证失败地址
      unauthorizedUrl: /unauth
      #首页地址
      indexUrl: /index
      #验证码开关
      captchaEnabled: false
      #验证码类型: math数据计算、char字符检验
      captchaType: math
   cookie:
      #设置cookie的域名 默认为空，即当前访问的域名
      domain:
      #设置cookie的有效访问路径
      path: /
      #设置HttpOnly属性
      httpOnly: true
      #设置cookie的过期时间，单位为天
      maxAge: 1
   session:
      #session超时时间，-1代表永不过期（默认为30分钟）
      expireTime: 30
      #同步session到数据库的周期（默认1分钟）
      dbSyncPeriod: 1
      #相隔多久检查一次session的有效性，默认10分钟
      validationInterval: 10
      #同一个用户最大会话数，比如1的意思是同一个账号允许最多同时一个人登录（默认-1不限制）
      maxSession: 1
      #踢出之前登录的/之后登录的用户，默认踢出之前登陆的用户
      kickoutAfter: false
      
#swagger
swagger:
   #是否启用
   enabled: true
   #是否允许匿名访问
   anonAccess: true
      
#防止xss攻击
xss: 
   #过滤开关
   enabled: true
   #排除链接（多个用逗号分隔）
   excludes: /system/notice/*
   #匹配链接
   urlPatterns: /system/*,/monitor/*,/tool/*
      